[package]
name = "larsb/ragdollanimals"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
GameAnalytics = "gameanalytics/gameanalytics-sdk@2.2.6"
Cmdr = "evaera/cmdr@1.12.0"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.1"
ProfileService = "jakebball/profileservice@1.5.0"